In [40]:
### Assignment 1: Array Creation and Manipulation

#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements
#  in the third column with 1.

import numpy as np
import random 

"""
a1 = np.arange(1,21).reshape(4,5)
a1[3:] = 1
a1

This code works just that the question is asking for random integers. So we will try the random module. 
"""

#1.

a2 = np.random.randint(1,21,size=(5,5))
a2[:,2] = 1
a2

array([[ 5, 12,  1, 18,  8],
       [11, 18,  1, 20, 16],
       [11,  9,  1,  4, 17],
       [ 4,  6,  1, 18,  2],
       [ 3,  8,  1, 14, 11]], dtype=int32)

In [71]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

a3 = np.arange(1,17).reshape(4,4)
np.fill_diagonal(a3,0)
a3

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [76]:
### Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 
# 5th rows and 2nd to 4th columns.

arr1 = np.arange(1,37).reshape(6,6)
print(arr1)
arr1[2:5,1:4]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [100]:
#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

# This is one method to solve, but it changes the original array in the process. 

a2 = np.random.randint(1,11,size = (5,5))
print(a2)

#a2[1:4,1:4] = 0
#a2[a2>0]

[[10  3 10  3  2]
 [ 4  9 10  8  5]
 [ 5  6 10  7  1]
 [ 4  1  3  2  2]
 [ 4  3  6  6  4]]


In [122]:
# Different method: 

a2 = np.random.randint(1,11,size = (5,5))
print(a2)
np.concatenate((a2[0,:],a2[-1,:],a2[:,0],a2[:,-1]))

[[10  8 10  9  2]
 [10  2  8  6  3]
 [ 7  2  5  3  9]
 [ 6  3  5  4  6]
 [ 8  5  9  1  9]]


array([10,  8, 10,  9,  2,  8,  5,  9,  1,  9, 10, 10,  7,  6,  8,  2,  3,
        9,  6,  9], dtype=int32)

In [134]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, 
# subtraction, multiplication, and division.

arr3 = np.random.randint(1,10, size = (3,4))
arr4 = np.random.randint(1,10, size = (3,4))

print(arr3 + arr4,"\n")
print(arr3 - arr4,"\n")
print(arr3 * arr4, "\n")
print(arr3 / arr4, "\n")

[[ 8  7 16 18]
 [13 13 11 15]
 [14  8  8  8]] 

[[ 0 -3  0  0]
 [-3 -3  7  1]
 [ 0 -2 -6 -4]] 

[[16 10 64 81]
 [40 40 18 56]
 [49 15  7 12]] 

[[1.         0.4        1.         1.        ]
 [0.625      0.625      4.5        1.14285714]
 [1.         0.6        0.14285714 0.33333333]] 



In [161]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr5 = np.arange(1,17).reshape(4,4)
print(arr5)

# Manual method
b = np.split(arr5,4)
print("\n", b[0] + b[1] +b[2] + b[3])

c = np.split(arr5,4,axis = 1)
print("\n", c[0]+c[1]+c[2]+c[3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 [[28 32 36 40]]

 [[10]
 [26]
 [42]
 [58]]


In [162]:
# Efficient method: 

arr5 = np.arange(1,17).reshape(4,4)
print(arr5)

row_sum = np.sum(arr5, axis=0)
column_sum = np.sum(arr5, axis=1)

print("row_sum: ", row_sum)
print("column_sum: ", column_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row_sum:  [28 32 36 40]
column_sum:  [10 26 42 58]


In [163]:
arr1 = np.array([1,2,3,4])

np.sum(arr1)

np.int64(10)

In [171]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation,
#  and variance of the array.

arr1 = np.random.randint(1,10, size = (5,5))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))

4.4
4.0
2.7422618401604177
7.52


In [173]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to 
# have a mean of 0 and a standard deviation of 1).


arr2 = np.arange(1,10).reshape(3,3)

Mean = np.mean(arr2)
Standard_dev = np.std(arr2)

# Normalization = (Array - Mean)/Standard_dev:

Normalized_array = (arr2 - Mean) / Standard_dev
print(Normalized_array)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [176]:
### Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row 
# of the 2D array using broadcasting.

arr4 = np.random.randint(1,10, size = (3,3))
print(arr4)
a1d = np.array([10,10,10]) # random array

print("\n",arr4 + a1d)

[[8 6 9]
 [2 6 3]
 [9 4 5]]

 [[18 16 19]
 [12 16 13]
 [19 14 15]]


In [188]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each
#  column of the 2D array using broadcasting.

arr5 = np.random.randint(1,17, size = (4,4))
ad1 = np.random.randint(1,5, size =(4,))

print("Original Array", "\n",arr5)
print("Column_array", "\n", ad1[:,np.newaxis])

print("Output_array","\n", arr5 - ad1[:,np.newaxis])


Original Array 
 [[14  7  9  3]
 [ 1  3 14 10]
 [ 9  1 10  1]
 [16  4 14  8]]
Column_array 
 [[1]
 [1]
 [4]
 [1]]
Output_array 
 [[13  6  8  2]
 [ 0  2 13  9]
 [ 5 -3  6 -3]
 [15  3 13  7]]


In [206]:
### Assignment 6: Linear Algebra

#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

ar1 = np.random.randint(1,10,size = (3,3))

det = np.linalg.det(ar1)
inv = np.linalg.inv(ar1)
eig = np.linalg.eigvals(ar1)

print("Determinant: ",det)
print("Inverse: ","\n", inv)
print("Eigen_values: ", "\n", eig)

Determinant:  -31.99999999999993
Inverse:  
 [[-0.125   0.75   -0.875 ]
 [ 0.4375 -1.375   1.5625]
 [-0.5     1.5    -1.5   ]]
Eigen_values:  
 [15.79309906  6.51777416 -0.31087322]


In [212]:
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

ar2 = np.random.randint(1,10,size = (2,3))
ar3 = np.random.randint(1,10, size = (3,2))

# Matrix Multiplication is basically mutiplying a row of one matrix with column of another. 
# Its also called the dot product and can be done using np.dot(array1, array2) 

print(np.dot(ar2,ar3))

[[95 36]
 [31 16]]


In [214]:
### Assignment 7: Advanced Array Manipulation

#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to 
# shape (9, 1).

new_array = np.arange(1,10).reshape(3,3)
print(new_array.reshape(1,9))
print("\n",new_array.reshape(9,1))


[[1 2 3 4 5 6 7 8 9]]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [219]:
#2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back
#  to (5, 5).

arr1 = np.random.randint(1,11, size = (5,5))
print(arr1.reshape(1,25))
print("\n",arr1.reshape(5,5))


# we can also use .flatten() method to flatten any matrix: 
print(arr1.flatten())


[[ 1  4  9 10  8  7  7  5  8  2  5  5 10  9  6  9 10  1  6  6  2  4  5  2
   4]]

 [[ 1  4  9 10  8]
 [ 7  7  5  8  2]
 [ 5  5 10  9  6]
 [ 9 10  1  6  6]
 [ 2  4  5  2  4]]
[ 1  4  9 10  8  7  7  5  8  2  5  5 10  9  6  9 10  1  6  6  2  4  5  2
  4]


In [232]:
### Assignment 8: Fancy Indexing and Boolean Indexing

#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements 
# at the corners of the array.

arr2 = np.random.randint(1,10, size = (5,5))

print(arr2)
print(arr2[0,0], arr2[0,-1], arr2[-1,0],arr2[-1,-1])


[[3 6 2 4 4]
 [9 9 2 7 1]
 [1 6 9 8 8]
 [7 1 3 5 7]
 [4 3 2 6 9]]
3 4 4 9


In [233]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements 
# greater than 10 to 10.

arr3 = np.random.randint(1,20,size=(4,4))
print(arr3,"\n")
arr3[(arr3 > 10)] = 10
print(arr3)

[[14 13  5 14]
 [ 5  7  3  5]
 [10  3 10  6]
 [12 14  6 10]] 

[[10 10  5 10]
 [ 5  7  3  5]
 [10  3 10  6]
 [10 10  6 10]]


In [265]:
### Assignment 9: Structured Arrays

#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data 
# and sort the array by age.

DType = [("name","U10"), ("age", "i4"), ("weight","f4")]
arr = np.array([("krishna",26,103.5), ("SK", 25, 102.65), ("Raj", 28, 100.45)], dtype = DType)
print("Original_Array: ", arr)

sorted_arr = np.sort(arr, order = "age")
print("Sorted_array",sorted_arr)


Original_Array:  [('krishna', 26, 103.5 ) ('SK', 25, 102.65) ('Raj', 28, 100.45)]
Sorted_array [('SK', 25, 102.65) ('krishna', 26, 103.5 ) ('Raj', 28, 100.45)]


In [270]:
### Assignment 10: Masked Arrays

#1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the 
# sum of the unmasked elements.

a = np.random.randint(1,20, size = (4,4))
print(a)
mask = a>10
mask2 = a<10

print(a[mask2], sum(a[mask2]))

[[15  3 19  1]
 [18 11  2  3]
 [10 12 13 18]
 [ 5  2 15 14]]
[3 1 2 3 5 2] 16


In [ ]:
``