In [1]:
# Numpy is a fundamental library for scientific computing in Python. 

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [8]:
## Create arrays using Numpy
## 1-D Array: 

arr1 = np.array([1,2,3,4,5])
arr1


array([1, 2, 3, 4, 5])

In [9]:
print(type(arr1))

<class 'numpy.ndarray'>


In [10]:
arr1.shape

(5,)

In [14]:
arr2 = np.array([1,2,3,4,5])

arr2.reshape((5,1))  ## 2-D Array

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
arr2   #reshape was not an in-place change so the array will revert back to its original shape. 

array([1, 2, 3, 4, 5])

In [19]:
arr3 = np.array([[1,2,3,4,5,6,7,8]])
arr3

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [20]:
type(arr3)

numpy.ndarray

In [21]:
arr3.shape

(1, 8)

In [24]:
a = arr3.reshape(4,2)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
a.shape

(4, 2)

In [26]:
# Dimension is basically how many brackets inside the elements start visually. But in reality its the number of values to be given to access elements
# present inside an array or matrix. So for 1-D array you can directly access using directly the position, and for 3-D array you need to give 3 values
# to access the inside element. 

In [28]:
arr4 = np.array([[1,2,3],[4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr4.shape

(2, 3)

In [30]:
# in-built functions

In [31]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# By default the values are set to float, we can change it other data types. 

np.ones((4,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
np.identity(4) # within this matrix, the diagonal elements will be 1 and all the other elements will be 0. 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
arr5 = np.array([[1,2],[3,4],[5,6]])

In [45]:
## Some common Numpy attributes

print(arr5.shape)
print(arr5.ndim)
print(arr5.size) #Total number of elements
print(arr5.dtype)
print(arr5.itemsize) #Size of an indivisual element in bytes
print(arr5.nbytes) #Size of the entire array in bytes 

(3, 2)
2
6
int64
8
48


In [46]:
## Numpy Vectorized operations

In [50]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,11,12,13,14])


# Element -wise addition
arr1 + arr2

array([11, 13, 15, 17, 19])

In [51]:
# Element-wise Subtraction: 
arr1 - arr2

array([-9, -9, -9, -9, -9])

In [52]:
# Element-wise Multiplication: 
arr1 * arr2

array([10, 22, 36, 52, 70])

In [53]:
## Universal Function: 


arr = np.array([1,2,3,4,5])

# Square Root
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [54]:
# Exponential
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [55]:
#Sine: 
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [56]:
# Natural Log: 
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [57]:
## Slicing and Indexing: 

In [59]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [68]:
arr[1,1]

np.int64(7)

In [70]:
arr[0:3,0:1]

array([[1],
       [6]])

In [71]:
arr[0:,2:4]

array([[3, 4],
       [8, 9]])

In [73]:
# Modify array elements: 

arr[0,0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [74]:
arr[1:] = 100

In [75]:
arr

array([[100,   2,   3,   4,   5],
       [100, 100, 100, 100, 100]])

In [76]:
## Logical operations:

data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
type(data > 5)

numpy.ndarray

In [78]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [84]:
data[(data>5) & (data<8)]

array([6, 7])